### ISSUE TITLE
Self-Report First Delieverable - Sara Fernández Arias

### ISSUE THREAD

**Issue by FdezAriasSara** [Arquisoft/lomap_en3b#18]
# Sara Fernández Arias
## Assigned sections of the documentation

Issue #2  :Introduction and Goals
Issue #7:  V2 of Runtime view   ( v1 made by @Batuhanbyr )
Issue #16  : Design  Decisions
Issue #13 : v2. Of Deployment view ( v1 made by @Batuhanbyr )

## Other contributions 
- Attend all the meetings and participate in discusions about the architecture application
- Read inrupt documentation to try and understand how it works  (general schema ) in order to make the diagrams above
- Gather information regarding free hosting services  
## Tools used
- AsciiDoctor was used for the documentation.
- PlantUML for creating the diagrams.

**Comment by FdezAriasSara** [comment]
![image](https://user-images.githubusercontent.com/79209608/220972832-5b9d4f94-4681-443d-97ab-237ddaf03a48.png)
![image](https://user-images.githubusercontent.com/79209608/220972883-d352f8a8-3b8c-433f-abe6-d5cc8c987295.png)
![image](https://user-images.githubusercontent.com/79209608/220972911-b0d698dd-b648-4249-a5c8-49a005606505.png)
![image](https://user-images.githubusercontent.com/79209608/220972955-3719aa79-9e1e-4174-93f8-b3cc3284139f.png)

**Comment by juanmglzs** [comment]
👍🏽
