### ISSUE TITLE
Requierements, Stakeholders & Quality Goals

### ISSUE THREAD

**Issue by FdezAriasSara** [Arquisoft/lomap_en3b#2]

**Comment by FdezAriasSara** [comment]
Documentation on **Requirements Overview, Stakeholders & Quality Goals** from Arc42 regarding lomap.

**Comment by FdezAriasSara** [comment]
Finished v1.

**Comment by juanmglzs** [comment]
Too many quality Goals in 1.2

**Comment by juanmglzs** [comment]
Only 2/3 (the main quality goals)

**Comment by juanmglzs** [comment]
1.3. Stakeholders - Add all the teachers. 
Remove the map provider (?)
Add Inrupt and Other solid POD-apps

**Comment by FdezAriasSara** [comment]
Made changes proposed on the first deliever:

 - Left the most relevant quality goals: Privacy & responsiveness
 - Included all professors as stakeholders
 - Removal of Map provider from stakeholders 
 -  Inlcuded pod providers and inrupt as stakeholders.
