### ISSUE TITLE
Self Report - Second Deliverable PROTOTYPE

### ISSUE THREAD

**Issue by Manuhcuartas** [Arquisoft/lomap_en3b#35]
# Manuel Hernández Cuartas

## Functionality 

Login session management and handling of the lomap folder in the pod of the authenticated user.

## Documentation
	- Solved errors from first delivery 
	- Updated documentation with changes done after implementation.

## Research
Corresponding research in order to carry out the mentioned functionality (given examples and inrupt documentation).
	
I attended all the meetings and participated in every discussion.

**Comment by FdezAriasSara** [comment]
Thanks for your work on the session :)
