### ISSUE TITLE
Render pins from pods +  Filter map pins by categories.

### ISSUE THREAD

**Issue by FdezAriasSara** [Arquisoft/lomap_en3b#42]
- [x] Retrieve locations from the pod's resource and render their info in lomap when the user logs in.
- [x] Filter locations using categories 
- [x] optimize rerenders in location filtering.

- idea:  Giving the possibility to Import locations from more than one source?

**Comment by FdezAriasSara** [comment]
These days I've been working on parsing the data stored in resources inside /lomap folder. 
Unfortunately I wasnt able to make it as I wanted, with jsonld. So I'll stick to turtle for the moment so I can advance , since trying already stopped me from advancing for the last few days. (detailed in disccusion https://github.com/Arquisoft/lomap_en3b/discussions/51#discussion-5015158

I also  need to investigate a little more for including elements like comment arrays and "mixing" schema types.
For the moment, we will stick to this structure, and during the spring break i will try to enhance the data stored in locations.

Example of the current status:
```

@prefix loc: <http://schema.org/> .

loc:Loc_1 a loc:Place ;
    loc:identifier "ResidentEvilMockPlace";
    loc:name "Racoon City" ;
    loc:description "Everybody is so weird.." ;
    loc:latitude "43.35302550278352" ;
    loc:longitude "-5.849442050492078" ;
    loc:alternateName "city" .

loc:Loc_2 a loc:Place ;
    loc:identifier "MockBeach" ;
    loc:name "Silence Beach" ;
    loc:description "Amazing place" ;
    loc:latitude "43.565795088475504" ;
    loc:longitude "-6.296431272044736" ;
    loc:alternateName "beach" .
```

**Comment by FdezAriasSara** [comment]
![image](https://user-images.githubusercontent.com/79209608/228631467-d830e5ef-84f7-400b-8c99-24e169354439.png)
Functionality of rendering pins from pods included in commit  https://github.com/Arquisoft/lomap_en3b/commit/bea8b35b3337b70ab9ead27be12c1dbb0276deba?diff=split
 
Main things :

     //Convert into LocationLM object
               location= new LocationLM(

                    Number(getStringNoLocale(locationThing, SCHEMA_INRUPT.latitude)),               // CoorLat,
                   Number(getStringNoLocale(locationThing, SCHEMA_INRUPT.longitude)),              // CoorLng,
                    getStringNoLocale(locationThing,SCHEMA_INRUPT.name),            // name,
                    getStringNoLocale(locationThing, SCHEMA_INRUPT.description),     // description,
                    getStringNoLocale(locationThing, SCHEMA_INRUPT.alternateName),   // category
                );


Latitude and longitude are strings for Inrupt's Schema vocabulary, so I parsed them as locations and then transformed them into numbers.
I removed the constructor arg for id, since its generated,


Flow of execution of this functionality 
1º App starts and asks the user to login
2º Once the user logs in , we check for a lomap folder
3º In case such folder is available , we display MapView component, and while doing so , all functionality of reading locations from the pod is executed 
  For that, i pass the session object as a prop in<Map> component.
    In map component:

 ```
const retrieveLocations=async () => {
                  let resource = session.info.webId.replace("/profile/card#me", "/lomap/locations.ttl")
                  return await readLocations(resource, session);
              }
```
          in the previous snippet I call the method that makes the request and parses data into LocationLM objects
              const onMapLoad = React.useCallback((map) => {
                mapRef.current = map;
              }, []);
          
              React.useEffect( () => {
                  async function getAndSetLocations() {
                      let locationSet = await retrieveLocations()
                      setMarkers((current) => [...current, ...locationSet]);
                  }
          
                 getAndSetLocations();
              }, []);


> 
I use react's UseEffect to execute the code that makes the request and renders the pins.

**Comment by juanmglzs** [comment]
I don't understand the part that you removed the "id since it's generated". How will places (locations) and reviews be stored? How are we going to link them? 

Because my first approach is generated the ID only once and keep it during the life time of the Location. So we can use it to link the reviews to a specific locación and keep track of them when loading them into the pod as a separated things (Location and Review). 
This can help to load them in parallel to/into the pod and when loading them in our domain model used an argumento from Review "location_referred" (this will be the location I'd) to know what location is the review related to. 

I don't know if I did explain myself. If you have found a new way to do it, I'm all ears x

**Comment by FdezAriasSara** [comment]
> I don't understand the part that you removed the "id since it's generated". How will places (locations) and reviews be stored? How are we going to link them?
> 
> Because my first approach is generated the ID only once and keep it during the life time of the Location. So we can use it to link the reviews to a specific locación and keep track of them when loading them into the pod as a separated things (Location and Review). This can help to load them in parallel to/into the pod and when loading them in our domain model used an argumento from Review "location_referred" (this will be the location I'd) to know what location is the review related to.
> 
> I don't know if I did explain myself. If you have found a new way to do it, I'm all ears
> 
> PS: I did modified the Location class so when you create the object without is it is generated (add new location) but if you have it, it is reused (parsing from POD)

Hi I meant i removed the argument from the constructor not the parameter itself:
![image](https://user-images.githubusercontent.com/79209608/228661889-61aaac41-edfb-4b7a-9af7-9af4c960539b.png)
we were pasing a value that is never assigned. Sorry for the confussion


btw : I don't know if this affects you that much , but in location LM 
![image](https://user-images.githubusercontent.com/79209608/228662117-a1df1203-64f1-4a56-8ed1-efaa8e075d9a.png)
I was getting an empty array when parsing elements because in the condition, there where two !! 
like 


` if(!!value){
        throw new StringInvalidFormatException(new String(str + '=' + value));
    }`


I changed it in my commit but well so you know in case you're working with that too

**Comment by juanmglzs** [comment]
Thanks

**Comment by FdezAriasSara** [comment]
Hi @Batuhanbyr & @RaduSeba  I Just found out that the colors in the locations markers were not working because marker.type was being used instead of marker.category
![image](https://user-images.githubusercontent.com/79209608/230793043-8e682c3c-f330-48d7-a366-2903b425b277.png)

now it works as you guys intended  and its soo nice, thank you !
I  wanted to let you know just in case you were using that attribute anywhere else!
![image](https://user-images.githubusercontent.com/79209608/230793118-50a79f69-4d43-4bc9-91fd-32dd3eb3d7e2.png)
these are the current attributes locations have, ( inside  src/webapp/models/location.js)

**Comment by Batuhanbyr** [comment]
Thank you so much, I will be more careful. Your job is amezing thanks
