### ISSUE TITLE
Improve accessibility and responsiveness

### ISSUE THREAD

**Issue by FdezAriasSara** [Arquisoft/lomap_en3b#54]
- [x] Add closing options for all modals ,like a cross , so the user knows exactly how to do it
for example
![image](https://user-images.githubusercontent.com/79209608/230592570-7a61f91b-a1fa-4579-94e4-6e492c089dd2.png)

there , to close it you have to click back to the profile icon 
![image](https://user-images.githubusercontent.com/79209608/230592709-b105be24-647c-4f36-a003-c5045da1798c.png)
so the profile dialogue dissapears.

(the same happens when you click on every button of the header)

So it ends up like :
![image](https://user-images.githubusercontent.com/79209608/230593110-74264019-cade-4e39-95c2-c87d8751c269.png)

- [x] Allowing friend list to be expanded

![image](https://user-images.githubusercontent.com/79209608/230592782-4c70418f-4cf7-42b3-9068-9c78bc0e025f.png)

The aesthetics are really beautiful i think the only thing missing is to be able to expand it somehow, or at least that the list appears in a bigger space. Its difficult to read the names 
![image](https://user-images.githubusercontent.com/79209608/230593371-ebf2b096-c431-4d2c-b735-c2a2b1d24262.png)
 for example if you have a bigger screen it does not adapt to the size 

- [x] Overall responsiveness

if you could make it responsive that would be awesome thanks for your work <3

**Comment by Batuhanbyr** [comment]
### Hi Sara! I have added the close icon buttons you wanted and made the friend section bigger. To ensure compatibility with all screen types, I need to do a bit more research on "Responsive Web Design".

**Comment by FdezAriasSara** [comment]
> ### Hi Sara! I have added the close icon buttons you wanted and made the friend section bigger. To ensure compatibility with all screen types, I need to do a bit more research on _Responsive_ _Web_ _Design_

Hi for the filter part, I've reused the ListStyle.js you use :) I found a way to make it accesible with flexBox.

![image](https://user-images.githubusercontent.com/79209608/230734633-074242b4-ee0e-489a-823b-6936d3bc0e17.png)
![image](https://user-images.githubusercontent.com/79209608/230734672-1c4bba16-b2a7-4012-a511-3e5b9e87255b.png)


For the pin part i wanted to make the checkboxes grouped, so I made a smaller box (beige) inside the "general one" (white). Notice how the size changes when i make the screen smaller :) 


![image](https://user-images.githubusercontent.com/79209608/230734960-7d4a07dd-72f0-44fd-82ad-e2686253fb5f.png)

I think i to make all responsive is just to move the flex display declaration to the general stylesheet. and then use flexes in the components we want to create a new "box" for


Here are some resources I found useful.

https://www.youtube.com/watch?v=7_yRrrDMCwQ&ab_channel=JustinNothling (this tutorial is short and straighforward:) 
https://reactnative.dev/docs/flexbox


Hope it helps! :)  If you want me to make it i can

**Comment by FdezAriasSara** [comment]
Also, In order to achieve responsiveness we need to use relative measuerements.
For example, when i want to create a container, instead of putting a fixed size using px : 

i do the following:
![image](https://user-images.githubusercontent.com/79209608/230738231-c1db488b-6a8c-4589-ba9e-66e53ce24176.png)

vh stands for viewport height
there also exists vw (for width)  


also , theres a measurement for fonts called em

somethings tho, are better left in pixels (for example images)


heres a nicer explanation [relative measurements](https://www.freecodecamp.org/news/learn-css-units-em-rem-vh-vw-with-code-examples/)

**Comment by Batuhanbyr** [comment]
### Thank you for your explanations, I will try to learn this things and also make changes as you wanted :))
