### ISSUE TITLE
Restructuring of the privacy levels

### ISSUE THREAD

**Issue by Manuhcuartas** [Arquisoft/lomap_en3b#55]
I am developing the loading of the friends locations into the user's map right now and I am having a really hard time figuring out how to get those locations from the folder. This is because we use the current session in order to make an access request to the lomap folder in the pod. This way is impossible to get the locations from the folder of a friends' pod because we do not have the authentication of such friend. I am currently checking and revising the inrupt documentation and I do not really know what should we do regarding this topic because I do not find any kind of module in the API to perform an access request to a user (friend) without the session authenticated of SUCH user. 

Therefore I believe maybe a good solution is to rethink how we are managing the privacy levels of the locations. 

I would like to know your opinions on this and what you all think could be a good approach regarding this problem.

**Comment by Manuhcuartas** [comment]
I thought the same but it keeps giving me unauthorized access whenever I try to read the locations

**Comment by FdezAriasSara** [comment]
> I thought the same but it keeps giving me unauthorized access whenever I try to read the locations

That's probably because the file was not created with that access grant (not sure) , if you cant manage to make it i'll look it up when i finish filtering locations
