### ISSUE TITLE
Unitary Tests

### ISSUE THREAD

**Issue by FdezAriasSara** [Arquisoft/lomap_en3b#57]
-Unitary tests for rendering 
- [x] Login View
- [x] Header elements
- [x] Filter menu
- [x] Profile menu
- [x] Log Out
- [ ] Detailed information of a location 
- [ ] Review Section
- [x] Add new  location form
- [ ] Achieving an overall coverage of 80%

**Comment by FdezAriasSara** [comment]
I just realized I made a mistake when modifying the sonarcloud configuration file, that would make the coverage be equal to 0%

**Comment by FdezAriasSara** [comment]
Good morning,@pglez82 


I was not able to get sonarcloud to percieve any code coverage.


I tried it all:

*  changing sonar language from ts to js , since that's what we are using
* changing sonar exclusions since , again we are using javascript , and test will be *.test.js instead of *.test.ts
* i changed the depth /shallow  problem mentioned in Arquisoft Faq https://github.com/Arquisoft/faq/issues/42
* Also i changed the sonarcloud action version as you told me and as it's said in the faq too https://github.com/Arquisoft/faq/issues/45
* I changed the directory for the scanner  to _look_ at because i wanted to test some views outside the component folder 
*i tought for a second it could be that tests would not run when doing npm test... but they do?So another possible solution i think is discarded..
![image](https://user-images.githubusercontent.com/79209608/235346332-036facda-6e17-4dd5-b146-d16fc2ee16cd.png)

im trying to test more in depth, like functions being called, but i cannot always do that since some of them( the majority ) 
are handlers and are just arrowfunctions not being exported...


im not quite sure if the problem is sonarcloud file, my tests being bad or the way our code is that allows no coverage somehow?

here's the link to the sonarcloud report just in case it might be usefull..
https://sonarcloud.io/component_measures?metric=new_coverage&selected=Arquisoft_lomap_en3b%3Awebapp%2Fsrc%2Fcomponents%2FHeader.js&view=list&id=Arquisoft_lomap_en3b

I don't know what else to do with it..

Thank you in advance

Sara

**Comment by pglez82** [comment]
Can you add to package.json:

"test": "react-scripts test", the option --coverage?

Seems to me that it is not generating any coverage report.

**Comment by FdezAriasSara** [comment]
> Can you add to package.json:
> 
> "test": "react-scripts test", the option --coverage?
> 
> Seems to me that it is not generating any coverage report.


Thank you so much.. 
![image](https://user-images.githubusercontent.com/79209608/235374015-fbb63d6a-8f45-4e67-8a13-a53d850ba1f2.png)
