### ISSUE TITLE
Add marker List update 

### ISSUE THREAD

**Issue by RaduSeba** [Arquisoft/lomap_en3b#74]
## Adding add image and discription field 

![image](https://user-images.githubusercontent.com/98213239/233171777-a26ef125-b900-4ae3-b6d9-6efb464e08ee.png)

- We should add a text box with a description label in which the user can add a short description to the location he/she wants to add.
- Also I think they should also be able to add a picture of the location

Right now all these elemenmts are hardcoded. We should change it

**Comment by Batuhanbyr** [comment]
### I added an image upload section to the marker list, and also added an edit button to the info window. Please share your thoughts. @RaduSeba

https://user-images.githubusercontent.com/95686987/233496696-5a8f6285-164a-45ce-8b0e-6cda9ccff97d.mp4



https://user-images.githubusercontent.com/95686987/233496450-1f0c55d9-f534-4e8b-b8f5-a7041549a52e.mp4

**Comment by RaduSeba** [comment]
Great job!!!
