### ISSUE TITLE
Deployment error derived from sonarcloud

### ISSUE THREAD

**Issue by FdezAriasSara** [Arquisoft/lomap_en3b#77]
Good morning, @pglez82 

While trying to make our first, full deployment, we encontered the following problem:
![image](https://user-images.githubusercontent.com/79209608/233961532-cce79e01-fe08-4f5d-bd8b-669abb3c94f4.png)

I Tried the following things to solve it:
  - Removed the source of restapi from the file   [sonar-project.properties](https://github.com/Arquisoft/lomap_en3b/blob/master/sonar-project.properties)

  - To Comment out the [workflow file](https://github.com/Arquisoft/lomap_en3b/blob/master/.github/workflows/lomap_en3b.yml) lines related to sonar ( Even when i did this, sonarcloud is still run on the new release) 

Still, the same error appeared..

when looking in depth at the error this lines referencing some file / folder can be seen :
![image](https://user-images.githubusercontent.com/79209608/233963019-7251ddb1-b027-48b6-bd4a-cfebc652e001.png)

I tried searching for them in lomap but wasn't successfull , so im guessing is part of this [action](https://github.com/SonarSource/sonarcloud-github-action) and we cannot modify it?

 we were wondering if there's any other file we could, check /modify. Any information would be highly appreaciated

Thank you in Avance!

**Comment by pglez82** [comment]
Can you try this change in the actions configuration?

sonarcloud-github-action@master to sonarcloud-github-action@v1.8

**Comment by FdezAriasSara** [comment]
> Can you try this change in the actions configuration?
> 
> sonarcloud-github-action@master to sonarcloud-github-action@v1.8

Thank you so much that worked :)
