### ISSUE TITLE
Location Pictures

### ISSUE THREAD

**Issue by Batuhanbyr** [Arquisoft/lomap_en3b#84]
[LoMapPicture.zip](https://github.com/Arquisoft/lomap_en3b/files/11353211/LoMapPicture.zip)

@FdezAriasSara Hi, I have created different pictures for locations, and you can choose and use whichever one you prefer. I couldn't send them via WhatsApp, so I am sharing them here.

**Comment by FdezAriasSara** [comment]
Thank you so much batu :)
